

pipeline {

    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
				git 'https://github.com/nagabhushanamn/repo'
            }
        }
        stage('Test') {
            steps {
                dir('demo-app'){
					sh "mvn test"
				}
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}